Create project structure
ios-course/ironfoudation-team-project pull request #27
Opened 2023-05-03 10:24 UTC by NadzeyaShpakouskaya

## Summary

_This PR is a part of the work related to issue https://github.com/ios-course/ironfoudation-team-project/issues/1._
As [discussed and agreed](https://github.com/ios-course/ironfoudation-team-project/issues/19#issuecomment-1531313031) Model-View-ViewModel (MVVM) has been chosen as the architecture pattern. 
The code will be organized by layers.

### Changes

1. Add `Model` folder.
2. Add `View` folder.
3. Add `View Model` folder.
4. Add `Helper` folder.

2023-05-03 10:53 UTC, iBYarchitect approved these changes
LGTM

2023-05-03 11:30 UTC, iBYarchitect requested changes
I don't see folders for Model, View Model and Helper

2023-05-03 12:45 UTC, dersim-davaod requested changes
Same concerns as from @iBYarchitect 

@NadzeyaShpakouskaya make sure git stores your empty folders.
Either include some files into them or use `.gitkeep` files.

2023-05-03 13:16 UTC, julyakmita approved these changes
Thanks for the bug fixed! Now all  folders Model, View Model and Helper are visible.
 LGTM.

2023-05-03 14:11 UTC, iBYarchitect approved these changes
LGTM
nit: maybe it's good to change sitter.swift in model folder to .gitkeep?

2023-05-03 14:13 UTC, dersim-davaod approved these changes
LGTM

2023-05-03 17:10 UTC, NadzeyaShpakouskaya commented on Woof/Woof/Model/Sitter.swift
> +import Foundation
Fixed with [ec1a09d](https://github.com/ios-course/ironfoudation-team-project/pull/27/commits/ec1a09dae9afdd459b34e5d7c9158122f39f9148)
Replace the `Sitter` with `.gitkeep` as @iBYarchitect suggested.

2023-05-04 08:39 UTC, dersim-davaod approved these changes
LGTM

2023-05-04 08:41 UTC, merged