Create pet owner view for main tab
ios-course/ironfoudation-team-project pull request #47
Opened 2023-05-15 12:38 UTC by iBYarchitect

## Summary
This PR is related to the issue #15. 
Creating multiple structures necessary for displaying and editing information about a pet owner, as well as storing them in UserDefaults.

### Changes

- Edit `PetOwner`
- Add `OwnerCardViewModel`
- Add `OwnerCardView`
- Add `OwnerInformationView`

2023-05-15 14:47 UTC, dersim-davaod requested changes
Did a quick review; going to spend more time in few hours.

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +/// OwnerCardView is a SwiftUI view that displays the profile information in card view style of an Owner.
```suggestion
/// A view that displays the profile information of an Owner.
```

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +    @ObservedObject var viewModel = OwnerCardViewModel()
Missing doc.

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +    @State private var isEditMode: Bool = false
Missing doc.
Please review the rest of code.

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +                Image(systemName: "person.circle")
Shouldn't you use the image extension that your team has created?

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +                    .frame(width: 40, height: 40)
Magic numbers?

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +                        TextField("Adress", text: $viewModel.owner.address)
A typo:
```suggestion
                        TextField("Address", text: $viewModel.owner.address)
```

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +                    .background(isEditMode ? Color.App.purpleDark : Color.clear)
nit:
```suggestion
                    .background(isEditMode ? .App.purpleDark : .clear)
```

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/View/OwnerCardView.swift
> +                    .frame(width: 40, height: 40)
Please review the rest of code.

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/ViewModel/OwnerCardViewModel.swift
> +final class OwnerCardViewModel: ObservableObject {
I can't see any tests for the view model.

2023-05-15 14:47 UTC, dersim-davaod commented on Woof/Woof/ViewModel/OwnerCardViewModel.swift
> +        let encoder = JSONEncoder()
It violates the SRP and contradicts with the class's documentation.

2023-05-15 14:52 UTC, NadzeyaShpakouskaya requested changes
Consider some improvements

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/Model/PetOwner.swift
>  }
Maybe make sense to move the additional initializer to the extension, if we want to provide different types of initializer. What do you think?
```suggestion
   extension Owner {
    init(name: String, surname: String, phone: String, address: String, rating: Double){
        self.id = UUID()
        self.name = name
        self.surname = surname
        self.phone = phone
        self.avatarUrl = nil
        self.address = address
        self.rating = rating
    }
}
```

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +    @State private var isEditMode: Bool = false
Missed doc comments

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +                    }
I think we should discuss more how to present an unrated case because for me unfilled 5 stars also can mean a 5-star rating.

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +                    .foregroundColor(isEditMode ? Color.App.purpleDark : Color.App.purpleDark)
This line does nothing.
Maybe you want to change the font color for all cases to white and remove duplicate lines of code from the group section?

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +                    }
Do we need to display the rating view in editing mode, maybe we can hide it.

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +                        .foregroundColor(Color.App.white)
This is hard for me to distinguish the text from labels and button, maybe we can use any color or border to highlight it?

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/ViewModel/OwnerCardViewModel.swift
> +    }
Any test for this method?

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/ViewModel/OwnerCardViewModel.swift
> +        }
Should we create a separate method like for the `save` method and add tests?

2023-05-15 14:52 UTC, NadzeyaShpakouskaya commented on Woof/Woof/View/OwnerCardView.swift
> +                    Group {
It's better not to use numbers where it's possible and create a type-safe format for them, it also helps to follow the app style guidelines. Please review the all code below.

2023-05-16 08:42 UTC, julyakmita commented on Woof/Woof/View/OwnerCardView.swift
> +                    .frame(width: 40, height: 40)
Please, put this sizes in the file **UIElementSize.swift** in the **Helper** directory.

2023-05-16 08:44 UTC, julyakmita commented on Woof/Woof/View/OwnerInformationView.swift
> +/// A view representing the view of pet Owner profile information.
Nit:
A view representing the view of pet Owner's profile information.

2023-05-16 08:47 UTC, julyakmita requested changes
Good attempt!
Please, resolve the conflicts.

2023-05-16 12:45 UTC, julyakmita commented on Woof/Woof/View/OwnerInformationView.swift
> +/// A view representing the view of pet Owner profile information.
Nit:
```suggestion
/// A view representing the view of pet Owner's profile information.
```

2023-05-29 10:21 UTC, NadzeyaShpakouskaya commented
Closed due to high complexity.
The task was split into subtasks and the new PRs will be opened.

2023-05-29 10:21 UTC, closed without merging